### ISSUE TITLE
Companion Module Request - Seervision

### ISSUE THREAD

**Issue by Albinutte** [bitfocus/companion-module-seervision-suite#1]
I'm a developer at [Seervision](https://www.seervision.com/), a camera automation software. We provide an [API](http://api.seervision.com/) that can be used to use the system from various input sources, and we'd love to write a Companion module that would allow our users automate their workflow with Companion.

We've already developed a sample app during a hackathon, and I'd be happy to be able to make the module publicly available.   The [wiki](https://github.com/bitfocus/companion/wiki/Module-Development) page mentions the [BitFocus Slack](https://join.slack.com/t/bitfocusio/shared_invite/enQtODk4NTYzNTkzMjU1LTMzZDY1Njc2MmE3MzVlNmJhMTBkMzFjNTQ2NzZlYzQyZWIzZTJkZWIyNmJlY2U0NzM1NGEzNzNlZWY3OWJlNGE) channel, but I don't think I have access to it.

**Comment by josephdadams** [comment]
@Albinutte renamed branch to `main` (the new GH default).

Let me know if you would prefer repo to be named `companion-module-seervision-suite`.

To get your module included in the core beta builds (and any future public releases), you will need to join the Slack channel and ask in `module-development` for the module to get pushed into core. @krocheck or @JeffreyDavidsz will typically be the ones to do this.

https://join.slack.com/t/bitfocusio/shared_invite/enQtODk4NTYzNTkzMjU1LTMzZDY1Njc2MmE3MzVlNmJhMTBkMzFjNTQ2NzZlYzQyZWIzZTJkZWIyNmJlY2U0NzM1NGEzNzNlZWY3OWJlNGE

The module-adding and module-upgrading process is described here: https://github.com/bitfocus/companion/wiki/Module-Management

**Comment by Albinutte** [comment]
> Let me know if you would prefer repo to be named companion-module-seervision-suite

Yup, that would be great, thanks!

> you will need to join the Slack channel

I don't think I have access to it -- Slack demands an email with bitfocus domain from me.

![image](https://user-images.githubusercontent.com/8866457/123124524-0ade3280-d448-11eb-8bba-22fd9e79bc2c.png)

**Comment by Albinutte** [comment]
@josephdadams On a separate note, could you give write permission to this repo to @seervision-service? I'd like to set up mirroring from our main repo on GitLab, and I will use this service account to push changes automatically.

**Comment by josephdadams** [comment]
repo renamed and @seervision-service has write access now.

**Comment by josephdadams** [comment]
https://join.slack.com/t/bitfocusio/shared_invite/zt-o1i0mohx-p_m5I7fUEUJ1BBu_KrDN2Q

**Comment by Albinutte** [comment]
@seervision-service still doesn't have write access, could you try that again?

**Comment by josephdadams** [comment]
Re invited.
