### ISSUE TITLE
Version Update

### ISSUE THREAD

**Issue by maxchaos** [bitfocus/companion-module-seervision-suite#3]
Hello, I'm a developer at [Seervision](https://www.seervision.com/) and currently in charge of updating our companion module.

As you can see, a new version has been merged (and mirrored herein) resolving some compatibility issues with our suite's newer versions. Can you please inform me of what steps remain to be taken in order to incorporate these changes in mainstream companion?

Thanks in advance for your assistance.

**Comment by josephdadams** [comment]
Tag me on slack in the module-development channel that you have an update ready for betas. I know that seems counter intuitive but I get a ton of notifications here and it’s easier to track there especially if another core dev picks up putting it into core for you

**Comment by maxchaos** [comment]
Thank you for your time. It appears that I require an invite in order to join the indicated slack channel. Or is there another way?

**Comment by josephdadams** [comment]
https://join.slack.com/t/bitfocusio/shared_invite/zt-1ggdsufgh-BXLZssE7YaIzt5MD6a2low
